### ISSUE TITLE
Cook Config Not Found

### ISSUE THREAD

**Issue by r3dpoint** [pivotal-cf/docs-pcf-dev#31]
Trying to follow Use Spring Cloud Services and install the Cook App and Config. The Config Server has the following error: The Config Server cannot initialize using the configuration that has been provided. Please double-check the configuration and correct any mistakes. Is there an updated config URL? Here's the one in the documentation, which returns a 404:

{
	"count": 1,
	"git": {
		"label": "master",
		"uri": "https://github.com/spring-cloud-samples/cook-config"
	}
}

**Comment by animatedmax** [comment]
Hi @nsikha -- where in the documentation did you find this URL? I am having a difficult time locating it so that we can correct it.

**Comment by mdelillo** [comment]
@animatedmax I think @nsikha is referring to step 5 of [this page](https://docs.pivotal.io/pcf-dev/usage-scs.html#use-scs), and the new URL should be https://github.com/spring-cloud-services-samples/cook-config.

**Comment by animatedmax** [comment]
Thank you @nsikha for bringing this up, and @mdelillo for providing the correct URL (and showing me the topic where it was incorrect). We've corrected this in the documentation.
