### ISSUE TITLE
Documentation of PCF DEV setup with custom registries wrong

### ISSUE THREAD

**Issue by uromahn** [pivotal-cf/docs-pcf-dev#32]
Under the chapter "Insecure Docker Registries" this [file](https://github.com/pivotal-cf/docs-pcf-dev/blob/master/configuring.html.md.erb) contains the following:
"The -r flag adds support for custom insecure Docker registries."

This is either wrong or there is a bug in PCF DEV. When I setup a local "insecure" registry, i.e. a registry listening on HTTP and *not* HTTPS, and add this to my PCF DEV instance using the -r flag, I am getting the following error message:

>...
>Staging process started ...
>Failed to talk to docker registry: Get https://host.pcfdev.io:5000/v2/: http: server gave HTTP response to HTTPS client
>Staging process finished
>...

This tells me that either PCF DEV does not honor the "-r" flag or it may expect a "secure" registry but with a self-signed certificate. I suspect the latter because the documentation of the "-r" flag in PCF DEV (with `cf dev --help`) seems to indicate that:

`[-r registry1,registry2,...]   Docker registries that PCF Dev will use without SSL validation. Specify in 'host:port' format.`

It would be great if the documentation describes the correct way of doing it. It also would be great if developers would be given a recipe on how to setup a local Docker registry correctly since dealing with self-signed certificates is absolutely none-trivial!

**Comment by sclevine** [comment]
That docs page does say at the beginning:
> | `-r registry1,registry2,...`  | Specify Docker registries that PCF Dev will use without SSL validation. Use `host:port` format. |

I submitted #33 to remove the misleading wording. Happy to review a PR that adds instructions on how to setup a local Docker registry.

**Comment by pspinrad** [comment]
Thanks @sclevine !  Hey @uromahn, did that [change](https://github.com/pivotal-cf/docs-pcf-dev/pull/33) make it work?
