### ISSUE TITLE
dnsmasq instructions for linux should consider ubuntu NetworkManager

### ISSUE THREAD

**Issue by sworisbreathing** [pivotal-cf/docs-pcf-dev#37]
[work-offline.html.md.erb](/pivotal-cf/docs-pcf-dev/blob/6b6db6a7b961c91919450969ce6c214091c3204f/work-offline.html.md.erb#L50) provides information about setting up dnsmasq on linux for working with pcf dev. However, Ubuntu 14.04 and newer generally come with dnsmasq already set up and managed by NetworkManager.

On those systems the user should not need to install dnsmasq, and should put the configuration in `/etc/NetworkManager/dnsmasq.d/` instead of `/etc/dnsmasq.d`. The config can be reloaded via `service network-manager restart` (for Ubuntu 14.04) or `systemctl restart NetworkManager.service` (for Ubuntu 15.04 and up)

**Comment by mlimonczenko** [comment]
Thank you, @sworisbreathing!
