### ISSUE TITLE
Unable to browse to Apps Manager page

### ISSUE THREAD

**Issue by sunit-joshi** [pivotal-cf/docs-pcf-dev#42]
I've setup CF Dev correctly & can browse to the Spring demo app. However if I try to navigate to https://apps.dev.cfdev.sh, I keep getting a:

404 Not Found: Requested route ('apps.dev.cfdev.sh') does not exist.

rgds
SJ

**Comment by aemengo** [comment]
Hey @sunit-joshi, could you please reply with the exact command that you used to start CF Dev and possibly the terminal output?

e.g.
```
$ cf dev ...
Starting VM...
```

**Comment by sunit-joshi** [comment]
I just did:

cf dev start



Then from the Spring music folder (that I cloned)…

cf dev push 



And this works…



But when I try to visit the Apps Mgr. URL, I get the prompt about certificate from Safari, and when I continue this:


rgds
SJ

**Comment by ssisil** [comment]
Hi SJ -

Just a quick clarification - 

If you run `cf dev start` without the -f flag - you start the tool in open source Cloud Foundry mode - which does not contain Apps Manager and works against the api.dev.cfdev.sh URL.

When you run `cf dev start -f <.iso file>` - you start the tool in PCF mode - which contains Apps Manager but is currently broken against the api.dev.cfdev.sh URL.

**Comment by sunit-joshi** [comment]
Ok, thanks. Could you please send me the link to download the .iso? I’ll try with that then...

SJ

**Comment by ssisil** [comment]
https://network.pivotal.io/products/pcfdev

**Comment by ssisil** [comment]
@sunit-joshi - The latest release has been updated and should work correctly with api.dev.cfdev.sh

**Comment by sunit-joshi** [comment]
Any thoughts what’s happening here…it’s been churning for quite sometime now. I’m using an iso file for this run.

Also, is the “progress” indicators related to applying latest patches? Will this happen each time?



rgds
SJ

**Comment by ssisil** [comment]
Yeah - it takes 90 minutes to start up. Its basically running a full PAS on your machine - so it does take longer than just the open source CF Dev

Progress indicators are related to the services starting up.

**Comment by sunit-joshi** [comment]
Ok, it finished. However when I browse to the link below, I get “Safari cannot find the server!” Error.



rgds
SJ

**Comment by ssisil** [comment]
What is the name of the .iso? You have to use the latest version - which I released earlier today - pcfdev-pas.v.2.0.20.0-build.0.82.0.iso

If you use pcfdev-pas.v.2.0.18.0-build.0.75.0.iso, you will receive that error as you described

**Comment by sunit-joshi** [comment]
Ok, downloading now…

Rgds
SJ

**Comment by sunit-joshi** [comment]
Why does cf dev start recreate everything each time that takes a long time? Is there a better way? Should just be stopping the app?

rgds
SJ

**Comment by sunit-joshi** [comment]
Also, where’s the Vm created? I don’t see anything in my VirtualBox?





rgds
SJ

**Comment by sclevine** [comment]
If you just want to stop the app, you can use the `cf stop` command. `cf dev start` and `cf dev stop` are used to provision and tear down and entire local Cloud Foundry.

CF Dev uses the native hypervisors built-in to macOS or Windows 10+ to run the VM -- Virtualbox is no longer required.

**Comment by sunit-joshi** [comment]
Thanks! I did figure about Hyperkit when I saw it grabbing memory in Activity Monitor.

The cf dev start is time consuming though. I feel I’m faster just spinning containers via Docker.

SJ
