### ISSUE TITLE
How to connect to a private insecure docker registry via PCF DEV?

### ISSUE THREAD

**Issue by bsferreira** [pivotal-cf/docs-pcf-dev#43]
Hi, I've tried to follow this approach to connect to the registry (https://docs.pivotal.io/pcf-dev/configuring.html) but pcf is still trying to connect via https. Here's what I've tried:

`cf dev start -r 192.168.11.1:5000`

`cf login -a https://api.local.pcfdev.io --skip-ssl-validation`

`cf enable-feature-flag diego_docker`

`cf push my-app-kotlin -o 192.168.11.1:5000/my-app-kotlin:1.0`

and then I got this:

```
Pushing app my-app-kotlin to org pcfdev-org / space pcfdev-space as admin...
Getting app info...
Creating app with these attributes...
+ name:           my-app-kotlin
+ docker image:   192.168.11.1:5000/my-app-kotlin:1.0
  routes:
+   my-app-kotlin.local.pcfdev.io

Creating app my-app-kotlin...
Mapping routes...

Staging app and tracing logs...
   Creating container
   Successfully created container
   Staging...
   Staging process started ...
   Failed to talk to docker registry: Get https://192.168.11.1:5000/v2/: http: server gave HTTP response to HTTPS client
   Staging process finished
   Exit status 0
   Staging Complete
   Destroying container
   Successfully destroyed container

Waiting for app to start...
Start unsuccessful
```

Just for the sake of it I've also connected via ssh to pcf to check if I had connection to my private registry and it actually works:

`vcap@agent-id-pcfdev-0:~$ curl -X GET http://192.168.11.1:5000/v2/_catalog`
`{"repositories":["my-app-kotlin"]}`

Am I missing something? How to bypass insecure connections between PCF and Docker Registry?

Thanks.

**Comment by bentarnoff** [comment]
@ssisil Could I ask you to take a look at the above? Thanks!

**Comment by ssisil** [comment]
@sdawson-pivotal - wanted to pass this along to you

**Comment by sclevine** [comment]
@bsferreira The `-r` option for insecure registries just permits you to use a self-signed certificate for HTTPS. It does not allow for completely unencrypted HTTP connections.

**Comment by bentarnoff** [comment]
Thanks all. @bsferreira I'm closing this issue, but please let us know if you have feedback for the PCF Dev documentation.
