### ISSUE TITLE
pcfdev installation issues

### ISSUE THREAD

**Issue by bipadhy** [pivotal-cf/docs-pcf-dev#44]
Hi,
I am trying to install pcf dev in windows 10 pro. 
Pre-requisites for the installation are installed. But when I run the below command, Installation failed and gave below error.
Command: **cf install-plugin cfdev** 
Error: **Plugin cfdev v0.0.13 could not be installed as it contains commands with names that are already used: dev.**

**Comment by bentarnoff** [comment]
Thanks @bipadhy. @ssisil, could I ask you to look at the above?

**Comment by sdawson-pivotal** [comment]
Hi @bipadhy, try uninstalling and re-installing the plugin. Please run `cf uninstall-plugin cfdev` and then run `cf install-plugin cfdev`.

**Comment by bentarnoff** [comment]
Thanks @sdawson-pivotal. @bipadhy I'm closing this issue for now but please let us know if you have feedback for the PCF Dev documentation.
