### ISSUE TITLE
We need to run command "cf dev start -f FILEPATH/FILE", if we wanna to start pcf dev?

### ISSUE THREAD

**Issue by victordpg** [pivotal-cf/docs-pcf-dev#51]
It takes long time to start pcf dev. 
Are there a quick way to start pcf dev, after 1st time started successfully?
Or we need to run the command "cf dev start -f FILEPATH/FILE" each time start?

**Comment by sdawson-pivotal** [comment]
Correct: to start pcf dev you do need to run `cf dev start -f FILEPATH/FILE` 
However you can deploy services when pcf dev is running using command `cf dev deploy-service SERVICE NAME`

What is your reason for starting/re-starting?
