### ISSUE TITLE
Link for Windows installer points to the internal releases

### ISSUE THREAD

**Issue by marcello-dev** [pivotal-cf/docs-pcf-dev#52]
The [link](https://github.com/pivotal-cf/docs-pcf-dev/blob/b546c3ac73ce10ac5af7ae098dec4fed8325e9fd/install-windows.html.md.erb#L43) for the Windows installer points to the internal releases, where the latest was in 2016.

In my opinion would be better to point to the [release page](https://network.pivotal.io/products/pcfdev/releases).

**Comment by mlimonczenko** [comment]
Hello @marcello-dev,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
