### ISSUE TITLE
Deploy service SCS failes on pcfdev due to expired certs.

### ISSUE THREAD

**Issue by PiNh00fD** [pivotal-cf/docs-pcf-dev#54]
Hi,

I'm playing with pcfdev on my linux box and want to experiment with SCS, more specific, spring cloud server to store secrets.
The installation failes with exitcode 1.
I had this issue before and that was due to expired certificates. I think the same issue is back.
Error in the install log:

Service broker error: Could not find an available leader from [https://10.144.0.13:8443]

When I bosh ssh into  my dedicated-mysql-broker and grep certificates in /var/vcap/sys/logs/*/*log I see:

broker/broker.log:[dedicated-mysql-adapter] 2021/01/20 17:31:29 Couldn't get read only information about URL https://10.144.0.13:8443, error: &errors.errorString{s:"GET https://10.144.0.13:8443/status failed: Get https://10.144.0.13:8443/status: x509: certificate has expired or is not yet valid"}

Is there still maintenance on the product?

**Comment by mlimonczenko** [comment]
Hello @PiNh00fD,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
